services:
  # Frontend Web Service
  - type: web
    name: frontend-service
    runtime: image
    image:
      url: docker.io/suhan06/social_media_frontend:latest
    plan: free
    envVars:
      - key: PORT
        value: "3000"
      - key: BACKEND_URL
        fromService:
          type: web
          name: backend-service
          property: host

  # Backend Web Service
  - type: web
    name: backend-service
    runtime: image
    image:
      url: docker.io/suhan06/social_media_backend:latest
    plan: free
    envVars:
      - fromGroup: backend-secrets 
      - key: PORT
        value: "3001"
      - key: FRONTEND_URL
        fromService:
          type: web
          name: frontend-service
          property: host

      # Prisma Connection String
      - key: DATABASE_URL
        fromDatabase:
          name: my-managed-postgres
          property: connectionString

      # Key Value Redis Mappings
      - key: REDIS_HOST
        fromService:
          type: keyvalue
          name: my-managed-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: keyvalue
          name: my-managed-redis
          property: port

  # Managed Redis Service Definition
  - type: keyvalue
    name: my-managed-redis
    plan: free
    ipAllowList: []

databases:
  - name: my-managed-postgres
    plan: free
    postgresMajorVersion: "16"
    ipAllowList: []

envVarGroups:
  - name: backend-secrets
