services:
  # Frontend Web Service
  - type: web
    name: frontend-service
    runtime: image
    image:
      url: docker.io/suhan06/social_media_frontend:latest
    plan: free
    docker:
      port: 3000
    envVars:
      - key: BACKEND_URL
        fromService:
          type: web
          name: backend-service
          property: url

  # Backend Web Service
  - type: web
    name: backend-service
    runtime: image
    image:
      url: docker.io/suhan06/social_media_backend:latest
    plan: free
    docker:
      port: 3000
    preDeployCommand: npx prisma migrate deploy
    envVars:
      - fromGroup: backend-secrets 

      - key: FRONTEND_URL
        fromService:
          type: web
          name: frontend-service
          property: url

      # Prisma Connection String
      - key: DATABASE_URL
        fromDatabase:
          name: my-managed-postgres
          property: connectionString

      # Corrected Key Value / Valkey Redis Mappings
      - key: REDIS_HOST
        fromService:
          type: keyvalue
          name: my-managed-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: keyvalue
          name: my-managed-redis
          property: port

  # Corrected Managed Redis Service Definition
  - type: keyvalue
    name: my-managed-redis
    plan: free

databases:
  - name: my-managed-postgres
    plan: free
    postgresMajorVersion: "16"

envVarGroups:
  - name: backend-secrets
