services:
  redis:
    image: redis:7
    container_name: redis_social_media
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight_social_media
    ports:
      - "5540:5540"
    restart: unless-stopped

  postgres:
    image: postgres:15.3-alpine
    container_name: pg_service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: suhan
      POSTGRES_DB: social_media
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=en_US.UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d social_media"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local